### ISSUE TITLE
Add ability to run `injectJs`

### ISSUE THREAD

**Issue by asiniy** [keathley/wallaby#101]
I found [injectJs](http://phantomjs.org/api/webpage/method/inject-js.html) heavily important because it allows to use polyfills in the code. I'm working on it now

**Comment by keathley** [comment]
Thanks @asiniy. I'd be interested in seeing this implementation. There's a few things that are important to consider. It seems like injectJS is specific to phantom. Currently our only communication to phantom is through ghostdriver (the phantomjs webdriver implementation). If we're going to allow for injection of polyfills and other scripts we'll also have to make sure that it works with other drivers in the future. For now that would mean making sure your changes only impact the current phantom driver.

At a higher level, I'm curious as to why you would opt to inject the polyfill directly into phantom instead of including it as part of your asset compilation step.

**Comment by asiniy** [comment]
@keathley [phantomjs doesn't support promises](https://github.com/ariya/phantomjs/issues/12401) - that's it. So, I need this support, because I'm writing in ES6. I tried to inject this polyfill to the webpack build (it changes `output.path` depending on the ENV), but haven't understand how to do it. Maybe you can help me with that instead (and you'll save me tons of hours btw)?

**Comment by keathley** [comment]
@asiniy did you manage to get this resolved. IMO I think this is something that should be handled outside of wallaby in your specific asset setup. I'd rather focus on finishing up selenium support which will help with a lot of these issues anyway.

**Comment by asiniy** [comment]
@keathley yeah, I set up my build properly, everything works. I'm closing the issue
