### ISSUE TITLE
Node.click returns node 

### ISSUE THREAD

**Issue by aellispierce** [keathley/wallaby#134]
In the documentation, it states that Node.click should return a session.
(`click(t) :: Wallaby.Session.t`)

However, instead it is returning the node that was clicked, as seen here: https://github.com/keathley/wallaby/blob/v0.15.0/lib/wallaby/node.ex#L110

Am I reading the docs wrong? It seems like it would make more sense if it did indeed return the entire session, as a click presumably changes the state of the page.

**Comment by keathley** [comment]
Those types are definitely wrong. Sorry about that. This looks like it might be broken in master as well: https://github.com/keathley/wallaby/blob/master/lib/wallaby/browser.ex#L467.

The idea of click and all of the other actions, is that they shouldn't change the current scope. So for instance `click/1` should return the element since you're already focusing an element. `click/2` should return the parent and not the element that was clicked. It looks like `click/2` will break chaining since it doesn't return the parent. Would you want to submit a PR for this?

**Comment by aellispierce** [comment]
Ah okay, that makes sense. It looks like click/2 is what I will want then once it is correctly returning the parent. I'll work on a PR to get that done.

**Comment by keathley** [comment]
Thanks! Let me know if you have any questions.
