### ISSUE TITLE
BUG: all/2 not working

### ISSUE THREAD

**Issue by hisapy** [keathley/wallaby#165]
Given a page with 3 `.mdl-list__item`, when I do:
```elixir
all(page, Query.css(".mdl-list__item"))
```
I expect to get a list of all those elements. Instead, I get an empty list `[]`.

Moreover, when in the same page I do:
```elixir
find(page, Query.css(".mdl-list__item"))
```

I get the following error:

```bash
** (Wallaby.QueryError) Expected to find 1, visible element that matched the css '.mdl-list__item' but 3, visible elements were found.
```

**Comment by keathley** [comment]
Are these elements loaded with javascript? Or should they be there on the page load?

**Comment by PragTob** [comment]
Also if it doesn't, an HTML file to reproduce would be great :)

**Comment by hisapy** [comment]
Hey guys, 

The elements are generated with React. Anyways, I _restarted_ my test suite and `all/2` is working fine so I'm closing this issue now.

Thanks for your help

:)

**Comment by hisapy** [comment]
Just for the record, this is not working consistently. I think there is a problem with timing but I'm not sure if it's related to PhantomJS, Wallaby or my Phoenix app.

In order to achieve some less false positives, I had to increase the following:

```
config :webapp, Webapp.Repo,
  # other conf here
  ownership_timeout: 25_000
 
config :wallaby,
  max_wait_time: 20_000
```

Ideally, I think I shouldn't have to wait that much.

**Comment by keathley** [comment]
The issue here is that `all/2` doesn't wait at all. `all/2` is just an wrapper around `find(query(count: :any))`. When your tests are failing what is happening is that `all` is running before your javascript has finished loading / react has finished rendering. Because nothing is present on the screen `all` returns you an empty list. The way to fix this is to use a specific finder instead of `all`. Something like `find(page, css(".mdl-list__item", count: 3))` should fix it.

As a side note, I'm considering removing `all` along with all of the old api functions. It frequently causes issues like this and has very limited use since you can express the same thing with `find`. Sorry about the confusion.
