### ISSUE TITLE
Clicking Canvas Elements

### ISSUE THREAD

**Issue by CMaylone** [keathley/wallaby#180]
I have an application that centers around a graph drawn by the [Cytoscape.js](http://js.cytoscape.org/) library. I need a way to test clicking and selecting behaviors but the library uses canvas elements to draw the graph. Is there a way to select nodes within a canvas? Or a more naive approach, can I specify coordinates to simulate a click event?

Here is an example rendering: http://jsbin.com/releziresa/1/edit?html,output

**Comment by PragTob** [comment]
Huh, I don't think there is such an interface... I guess one of the questions (that I don't know the answer to) is whether one can access canvas elements through XPath, if so it'd be possible. E.g. in [`Query`](https://hexdocs.pm/wallaby/0.16.1/Wallaby.Query.html#content) you can build all sorts of queries, among them xpath which is probably the most flexible

**Comment by keathley** [comment]
I think the only way to make this work is to use coordinates and mouseDown / touchStart events. The app that we originally built Wallaby for needed something similar. The way that we solved it was to use `execute_script` and executed the mouse moves and click events from JS.

It could be convenient to have some basic primitives like `pointer_move`, `pointer_down`, etc. handled by Wallaby. That would enable us to solve problems like #43. Just thinking now but the most useful might be something like `move_within(Element.t, xCoord, yCoord)`. That way you could specify relative coordinates to your canvas window which should (hopefully) match up with the code on the client side.

My only concern is that anything regarding canvas is going to have to be scripted by hand and thus somewhat error prone. There's not a lot that we can do about that. SVG is easier because they're real dom elements that we can query with xpath. But I'm not sure that means we _shouldn't_ support a high-level api for pointer actions.

What are your thoughts @PragTob?

**Comment by PragTob** [comment]
I think a high level API for pointer interactions will ultimatively be useful fo people for a number of reasons, so I'm all :+1: for it.

At the same time, it's not at the top of my pirority list as of now as there's still lots of other stuff to do before I'd get my hands on that :D

**Comment by keathley** [comment]
If I can get #174 fixed up then I can take a look at this. Otherwise @CMaylone if you're interested in working on this I can give you a detailed list of what would need to happen.

**Comment by CMaylone** [comment]
Sounds great! I would be willing to give it a shot. Full disclosure, my only Elixir experience was adding this library to my existing (non-Elixir) project. It might take me some time to ramp up.

**Comment by PragTob** [comment]
@CMaylone not that wallaby isn't awesome, but if your project isn't elixir you might have more success with [capybara](https://github.com/teamcapybara/capybara) and [poltergeist](https://github.com/teampoltergeist/poltergeist) from the ruby world as the projects are already more mature and might already have the functionality you are looking for + x.

Still, contributions heartfully welcome :)

**Comment by keathley** [comment]
Going to close this for now. It might be nice to do this in the future but currently I don't have bandwidth to support it. Feel free to re-open if anyone gets inspired.
