### ISSUE TITLE
Reinstate dialyzer spec checking in travis build

### ISSUE THREAD

**Issue by PragTob** [keathley/wallaby#186]
Removed in #185 due to random failures would be great to have again.

**Comment by PragTob** [comment]
Important input from @nobbz

> Exit code 137 means that a process is killed because the system went out of memory. There is no timeout happening, but dialyzer is quite hungry for memory, I'm not sure if there are many options to adjust.

**Comment by keathley** [comment]
Are the timeouts due to the PLT generation step? If so, is it possible to cache the PLT on AWS or something similar?

**Comment by aaronrenner** [comment]
I'm looking into the PLT generation error this morning. Here are a couple of things I'm trying:

1. Running with `sudo: required` so we get to run on a [vm with 7.5GB of memory](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments).
2. Using [`travis_wait`](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received) to make sure we don't time out if we don't receive output for 10 minutes while the plt is being generated.

Once the PLT is built and in our cache the builds should be quick. I also did see a [prebuilt PLTs repo](https://github.com/danielberkompas/travis_elixir_plts) that could be helpful, but I'm not sure how it will work since we are adding an additional application (inets) to our plt. It will definitely be worth looking into if the above options don't work.
