### ISSUE TITLE
Small default window size 

### ISSUE THREAD

**Issue by philliplongman** [keathley/wallaby#271]
The default PhantomJS window size is 480 x 800, which isn't terribly useful for taking screenshots.

I added a line in my FeatureCase to resize the window, but maybe it would be a good idea to increase the default size.

**Comment by keathley** [comment]
Thanks @philliplongman! There's an open issue about this here: #152. If you would like to submit a PR for this then that would be great. I'd be more then happy to discuss the necessary steps with you. Otherwise I'll probably won't get to it until after I finish the work to support chromedriver.

**Comment by philliplongman** [comment]
Well, I actually thought I'd take a stab at this. I forked the project and cloned it. But when I run `mix test.all` every test in the third set fails with `** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :econnrefused}}`. Tried uninstalling PhantomJS and reinstalling it via npm, but that didn't help.

**Comment by PragTob** [comment]
:wave: 

The README might not be too clear on it but it might very well be because you don't have chromedriver installed to run the selenium tests :)

**Comment by philliplongman** [comment]
Well, I just brew installed chromedriver and they still all fail. So I thought it might need me to start it before running the tests, but no dice.

**Comment by keathley** [comment]
Have you installed `selenium-standalone` and `geckodriver`? You'll need both of those for the selenium tests. You shouldn't need chromedriver yet since thats not merged to master atm. We definitely need to update the docs on how to get started doing development for wallaby.

In the meantime you should be able to run something like: `WALLABY_DRIVER=phantom mix test` which should run the integration tests for just phantom.
