### ISSUE TITLE
Allow users to override chrome version

### ISSUE THREAD

**Issue by keathley** [keathley/wallaby#276]
Right now we rely on chromedriver to select the correct chrome version. This should be configurable and allow users to specify whatever chrome installation they want.

**Comment by tk8817** [comment]
@florinpatrascu - feel like picking this up for fun?

**Comment by dsdshcym** [comment]
Hi, there!

I saw this issue from Elixir Starter and did some investigation.

It turns out to be hard for an Elixir library to control which chrome for chromedriver to use:
1. There is no argument for chromedriver to specify the chrome version (neither versions like 59 or 60, nor channels like stable, beta, or canary)
2. The official recommended way to use another version of chrome is to pass in the `binary` argument, see https://sites.google.com/a/chromium.org/chromedriver/capabilities#TOC-Using-a-Chrome-executable-in-a-non-standard-location

I think for now, the best way to use another version of chrome is changing chrome binary directly (during CI process or on local).

Let me know if I missed anything, and I would like to implement this feature if there is a grace way to do it.

**Comment by keathley** [comment]
@dsdshcym This should be possible once #309 is merged.

**Comment by dsdshcym** [comment]
@keathley cool, thanks for notifying me!

**Comment by michallepicki** [comment]
This seems to be possible since https://github.com/keathley/wallaby/commit/4b444350ecc22ce451ef7a379ac2e4a6b8a071b8 by specifying `:binary` path option
