### ISSUE TITLE
Headless Chrome -- best way to install?

### ISSUE THREAD

**Issue by jamonholmgren** [keathley/wallaby#302]
What's the best/easiest/quickest way to install headless chrome for use with Wallaby? Both on a Mac for development as well as Linux for CI.

**Comment by aaronrenner** [comment]
For OS X, you can run:
```
$ brew install chromedriver
```
This currently installs version 2.32 (2.31+ is required). Then you can either run `chromedriver` when  needed or have it always start with `brew services start chromedriver`. As long as you have Chrome 60+ installed, it should "just work".

As for running on Linux, here are the lines we added to our build script to get headless chrome running on Travis: https://github.com/keathley/wallaby/blob/master/.travis.yml#L40-L50.

For the time being, you will still need to have phantomjs installed on your machine as well. This is because wallaby has historically only supported phantomjs and still tries to start a pool of phantomjs processes on boot. I'm working on a fix for that and hope to remove that requirement soon.

Let me know if you have any issues!

**Comment by jamonholmgren** [comment]
@aaronrenner You're a collab on this project?? Nice! Thanks for the help, man, and great to see you last week at ElixirConf.

**Comment by aaronrenner** [comment]
@jamonholmgren Happy I could help. Feel free to reopen this issue of you have any other questions.

**Comment by mick352** [comment]
@aaronrenner : nowadays, it seems to be `brew cask install chromedriver`

**Comment by aaronrenner** [comment]
@mick352 Thanks posting this! ❤️
