### ISSUE TITLE
Example of usage with white-bread/cabbage

### ISSUE THREAD

**Issue by zedtux** [keathley/wallaby#333]
I'm completely new to Elixir/Phoenix and I'd like to use something like white-bread/cabbage in order to test my application but I'm lost on how to mix then with Wallaby.

Is there any kind of example project or guide somewhere I could have in order to figure this out?

**Comment by keathley** [comment]
I haven't used cabbage or white-bread before so I'm not exactly sure if this will be correct. But looking at the docs you should be able to do something like this:

```elixir
defmodule MyApp.Features.CoffeeTest do
  use Cabbage.Feature, async: false, file: "coffee.feature"
  use Wallaby.DSL
  import Wallaby.Query

  setup do
    on_exit fn -> # Do something when the scenario is done
      IO.puts "Scenario completed, cleanup stuff"
    end
    
    # Checkout a db connection and create a wallaby session
    :ok = Ecto.Adapters.SQL.Sandbox.checkout(YourApp.Repo)

    unless tags[:async] do
      Ecto.Adapters.SQL.Sandbox.mode(YourApp.Repo, {:shared, self()})
    end

    metadata = Phoenix.Ecto.SQL.Sandbox.metadata_for(YourApp.Repo, self())
    {:ok, session} = Wallaby.start_session(metadata: metadata)
    %{my_starting: :state, user: %User{}, session: session}
  end

  defgiven ~r/^there (is|are) (?<number>\d+) coffee(s) left in the machine$/, %{number: number}, %{user: user, session: session} do
    session
    |> visit("/some_page")
    |> click(css(".coffee-machine"))
    # ...
  end
end
```

If that works then we should think about adding an explanation to the wiki or something similar.

**Comment by zedtux** [comment]
Thank you @keathley for this quick help!! I will try it immediately.

**Comment by zedtux** [comment]
@keathley I tried it but got some incomprehensible error in my console and I'm too new to the stack to get ride it of it so I decided to go only with Wallaby ...

I still think that the documentation should cover this case so I let you decide what you want to do with this ticket. 😉

**Comment by keathley** [comment]
Thanks @zedtux. I'll see if I can get a demo application set up and work through the issues. If that all works I'll write a wiki entry for it.

**Comment by danielfoxp2** [comment]
Same here. I want to use White_Bread to describe my app behaviour with Wallaby to implement the steps. But Wallaby seems to be too much dependent of ExUnit configurations and therefore a real pain (to me) to configure with White_Bread. 

I do not want to use Cabbage, so I didn't test your suggested approach above. Can't you tell me if it is possible to make Wallaby work with White_Bread?

Thanks.

**Comment by keathley** [comment]
@danielfoxp2 There's nothing in wallaby that is tied to ExUnit. You could use wallaby from iex or any other process. Its not even specific to testing. You could use Wallaby to scrape webpages if you wanted to. Wallaby just drives browsers. We provide a setup for ExUnit since thats far and away the most popular test runner for Elixir. If you want to use an alternative test runner then thats perfectly fine. You'll just need to port the setup steps to your test runner of choice. We can't predict all the different combinations of tools that people are going to use. Honestly, I've been in the elixir community a long time and I'd never even heard of white bread.

That said, I took the time to figure out how to get white bread working for you. The example is here: https://github.com/keathley/wallaby_white_bread_example/blob/master/features/contexts/white_bread_context.exs. Based on my experience getting everything set up I suspect white bread is going to be finicky to work with. Its definitely still a work in progress. But if you want to go that route that example app should get you started.

**Comment by danielfoxp2** [comment]
I am reaally grateful by the example you gave. Thank you.

About the ExUnit dependent, I apologize. On elixir apps configurations I still struggle a lot. I was following the docs and not having a good time. I should've stated that it was a problem with my knowledge.

> You'll just need to port the setup steps to your test runner of choice
There is where I fell short.

Thank you to take the time to put the effort needed to do the example.

**Comment by keathley** [comment]
@danielfoxp2 No worries :)
