### ISSUE TITLE
Visit should throw an error when loading fails

### ISSUE THREAD

**Issue by paulcsmith** [keathley/wallaby#35]
I forgot to add `server: true` to my endpoint so when I attempted to visit the page nothing was rendered. The `visit` did not fail though, it continued on as if it loaded.

I think that if loading fails it should raise. It would be extra cool if the error message said something like this:

``` elixir
could not load #{the_full_url}. If you are using Phoenix you may need to enable the server

# config/test.exs
config :your_app, YourApplication.Endpoint,
  server: true
```

**Comment by keathley** [comment]
This one is slightly tricky. The relevant webdriver endpoint info is here: https://www.w3.org/TR/webdriver/#dfn-get. We'll need to see if Phantom actually behaves according to the spec or not. If it is then we should be getting an error back from Phantom. If its not then we'll have to find an alternative solution.

**Comment by keathley** [comment]
I did some more research into this. The short version is that phantom is behaving "as expected" by not returning an error. This sorta makes sense. A 404 page still "loads" successfully. Its just that the page doesn't exist. I think that there is a couple of other ways to handle this.

If we just want to remind the user to enable their server then we could look for that configuration flag if its a Phoenix application. Otherwise we'll need to define some semantics for what a "page load" really means and what sort of page loads should result in an error.

**Comment by keathley** [comment]
There isn't a great way to manage this currently without adding deeper hooks into a given framework which I'm leery to do currently. I'm going to close this for now since I'm not sure we have a good solution or that this needs to be fixed at a driver level.
