### ISSUE TITLE
Should take_screenshot return a session?

### ISSUE THREAD

**Issue by paulcsmith** [keathley/wallaby#37]
I tried this while debugging

```elixir
visit("/path")
|> take_screenshot
|> find(".my-css")
```

But it failed because `take_screenshot` did not return a session. I think it would be pretty cool if it returned a session so debugging with screenshots would be a bit simpler

**Comment by keathley** [comment]
Currently we return a `%{session: session, path: path}` where the path is the path to the screenshot. It probably makes more sense just to return the session since I think that most people are going to treat taking screenshots as a side-effect and not as something that they want to get the screenshot itself from.

**Comment by paulcsmith** [comment]
Yeah I think you're right about that!

**Comment by paulcsmith** [comment]
If later on you did want to let people do something with it, you could add another key to the session map/struct for `screenshot_path`. That way it's chainable, but could also be used to get the screenshot path

**Comment by keathley** [comment]
I think the best thing to do is to add a `screenshots` list to the session and then push the screenshot path into the list. That way you can keep track of multiple screenshots during a session.

**Comment by keathley** [comment]
I'm going to push a new release soon which should include this fix.
