### ISSUE TITLE
Add selected to query api

### ISSUE THREAD

**Issue by keathley** [keathley/wallaby#380]
There is currently no way to specify if a value is "selected" at the query level. This means if you want to assert an element is selected you need to do this:

```elixir
session
|> find(elem, fn e -> assert Element.selected?(e) end)
```

This is error prone since its no longer declarative and has race conditions.

We need to add `selected` to our list of query attributes.

**Comment by mhanberg** [comment]
I'm going to start working on this

**Comment by germsvel** [comment]
I was doing some preliminary research on this, and I had a couple of questions. Sorry for the long questions; let me know if they're not clear, and I can elaborate more. 

---

The first one is just a clarifying question: 

Is the intention of this to create something like this? (just want to confirm before diving in)

```elixir
session
|> find(Query.selected("#option-1"))
```

---

The second question is about the argument being passed into `Query.selected/1` (assuming the first question is correct). I know most of the form elements (e.g. `checkbox`) take a selector which could be a [name, id text, or label text](https://hexdocs.pm/wallaby/Wallaby.Query.html#module-form-elements). Was the intention for this to use xpath behind the scenes or a css selector?

I ask, because apparently xpath is [unable to find an option that is currently selected](https://stackoverflow.com/a/17988465) doing something like this `.//option[@selected='selected']`. I tested that with the `forms.html` fixture, and we can find the default selection, but it will not find the element selected if it has been changed. So it seems we _cannot_ use xpath for `Query.selected/1` (unless there's another way I'm unaware of). 

It does seem like we could use the css selector [:checked](https://developer.mozilla.org/en-US/docs/Web/CSS/:checked), but then we wouldn't be able to search by label text (e.g. `Query.selected("Option 1")`. We could let it be a css selector, and we append `:checked` to it: 

```
# tests
Query.selected("#option-1")

#compiled
{:css, "#option-1:checked"}
```

I'm not sure if it makes sense to go with css selectors or not here. So I'd be curious to hear your thoughts on it.

**Comment by keathley** [comment]
Sorry for the delay @germsvel and thanks for looking into this.

As for the first question I was originally thinking of something like this: `css("#option-1", selected: true)`. That way we can use our existing queries but determine if they are selected or not. As for implementation I think we may have to do something similar to how we check for visibility. The way that works is we find all the elements that match the original selector and then filter them based on the other provided options. There is a `selected` webdriver call that the driver module should already support.

Let me know if you have other questions or if that doesn't make sense.

**Comment by germsvel** [comment]
No delay at all! I know you're trying to step down from maintaining Wallaby, and I know it takes a lot to respond to all of the issues that come in. So thank you so much for taking the time! I really do appreciate it.

And thanks for the clarification. That makes it super clear, and I'm glad I asked the question. I was totally going the wrong way. I'll take a stab at it, and see where it goes.

**Comment by germsvel** [comment]
I took a stab at this in https://github.com/keathley/wallaby/pull/402. Let me know if it makes sense or if I should change stuff. Hope this helps, and thanks again for your time!
