### ISSUE TITLE
accept_dialogs function not found after upgrading to 0.21.0

### ISSUE THREAD

**Issue by sublimecoder** [keathley/wallaby#415]
## Issue

accept_dialogues showing as missing function after upgrading from 0.20.0 to 0.21.0.

```bash
   undefined function accept_dialogs/1
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/code.ex:767: Code.require_file/2
    (elixir) lib/kernel/parallel_compiler.ex:209: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

## Test Code & HTML

``` elixir
    session
    |> accept_dialogs
    |> sign_in(user)
    |> click(link("Subscription"))
    |> click(link("Reactivate Subscription"))
    |> take_screenshot()
    |> assert_has(css(".alert", text: "Subscription successfully reactivated"))
    |> assert_has(css(".subscription-status", text: "Active"))
```
It never gets to where its trying to parse the code. Elixir just seems to thinkk accept_dialogs just doesn't exist anymore.

**Comment by keathley** [comment]
Hey @sublimecoder sorry for the inconvenience. I broke my own rule about not doing breaking api changes and I'm sorry about that. These functions were removed in wallaby 0.21 in favor of using the more specific `accept_dialog`. `accept_dialogs` was really only there in order to deal with some phantom issues early on.

**Comment by sublimecoder** [comment]
Ah ok. Thanks for clarifying that.
