### ISSUE TITLE
Zombie process still there

### ISSUE THREAD

**Issue by popo63301** [keathley/wallaby#416]
Hello world! 

I'm using wallaby 0.21.0 and I have PhantomJS zombie processes. I know there have been some PR for fixing this but it seems that processes are not being killed after the work. What should I do?

**Comment by keathley** [comment]
Hey @popo63301 sorry to hear that this is still a problem. We're actively trying to move people away from phantom towards using the headless chrome driver. I know that's not a very satisfying answer but to be honest I'm not sure we're ever going to fully solve these problems with phantom especially since phantom is eol.

**Comment by popo63301** [comment]
Hi @keathley  ! Thank you for your answer.

For the moment, I decided to move to Rails for a specific project but I plan to get back to Elixir ASAP and use Wallaby as a solution for feature testing, so not having a solution yet is okay. I wish I could contribute as well on this project (when I will get more time). By the way, why did you chose chrome driver? is it because it is faster or simply the only alternative besides PhantomJS?

**Comment by keathley** [comment]
Its the most lightweight alternative to phantom IMO.
