### ISSUE TITLE
(FunctionClauseError) no function clause matching in Wallaby.Browser.find/3

### ISSUE THREAD

**Issue by pieterdub** [keathley/wallaby#475]
## Issue

I have setup my test exactly how it was shown in the examples but still get this error. It's able to load the test and navigate to the first page the (visit)

## Test Code & HTML

config set to use `Wallaby.Experimental.Chrome`
chrome version is : 78.0.3904.70

```
defmodule App.Features.UserTest do
  use App.FeatureCase, async: true

  import App.Factory
  import Wallaby.Query, only: [button: 1]

  test "user login", %{session: session} do
    insert(:user, email: "user@concord.com", password: "MyPasswordIsValid")

    session
    |> visit("/sign-in")
    |> fill_in("Email", with: "user@concord.com")
    |> fill_in("Password", with: "MyPasswordIsValid")
    |> click(button("Sign In"))

  end
end
```
error as follows:

```test/features/user_feature.exs:7
     ** (FunctionClauseError) no function clause matching in Wallaby.Browser.find/3

     The following arguments were given to Wallaby.Browser.find/3:
     
         # 1
         %Wallaby.Session{driver: Wallaby.Experimental.Chrome, id: "5dddbabe219157e3aee26fa42dffdbe7", screenshots: [], server: Wallaby.Experimental.Chrome.Chromedriver, session_url: "http://localhost:50349/session/5dddbabe219157e3aee26fa42dffdbe7", url: "http://localhost:50349/session/5dddbabe219157e3aee26fa42dffdbe7"}
     
         # 2
         "Email"
     
         # 3
         #Function<3.52831930/1 in Wallaby.Browser.fill_in/3>
     
     Attempted function clauses (showing 1 out of 1):
     
         def find(parent, %Wallaby.Query{} = query, callback) when is_function(callback)
     
     code: |> fill_in("Email", with: "user@concord.com")
     stacktrace:
       (wallaby) lib/wallaby/browser.ex:671: Wallaby.Browser.find/3
       test/features/user_feature.exs:12: (test)
```

**Comment by michallepicki** [comment]
Hi! Thanks for the detailed report.

I assume [these](https://hexdocs.pm/wallaby/readme.html#finding) are the examples you followed, am I right? If not, please let us know - there may be something wrong with the documentation.

In any case, in your stacktrace we can see that the error happens on line 12:

```
code: |> fill_in("Email", with: "user@concord.com")
```

Looking at [`fill_in` documentation](https://hexdocs.pm/wallaby/Wallaby.Browser.html#fill_in/3), its arguments should be: a `parent` (which can be either a session or an element to search in), a `Query` that describes how to find the input element, and a `with` keyword option that says how to fill in the input.

In your code I see that you passed `session`, `"Email"`, and `with: "user@concord.com"`. The second argument is wrong - it should be a Query. To construct a query you can use helper functions from the `Query` module, for example `text_input` seems suitable here. If you take a look at the example from Readme I linked to earlier, this is how it's done there (through a module attribute).

The error is showing up in `find` because `fill_in` just passes it the parent and query arguments without checking that they are correct. This may change in the future, which could improve the error message.

Let us know if there's anything else you need!
