### ISSUE TITLE
fill_in doesn't find elements by ID or label

### ISSUE THREAD

**Issue by jaimeiniesta** [keathley/wallaby#51]
Hello, I have a signup form:

```html
<form accept-charset="UTF-8" action="/signup" method="post">
  <input name="_csrf_token" type="hidden" value="...">
  <input name="_utf8" type="hidden" value="✓">
  
  <div class="form-group">
    <label>Name</label>
    <input class="form-control" id="user_name" name="user[name]" type="text">
  </div>

  <div class="form-group">
    <label>Email</label>
    <input class="form-control" id="user_email" name="user[email]" type="text">
  </div>

  <div class="form-group">
    <label>Password</label>
    <input class="form-control" id="user_password" name="user[password]" type="password">
  </div>

  <div class="form-group">
    <input class="btn" type="submit" value="Submit">
  </div>
</form>
```

Then, on the Wallaby test, I try to fill the inputs (Name, Email, Password). I've tried this: 

```elixir
fill_in(session, "Name", with: "Jaime")
```

and also this:

```elixir
fill_in(session, "#user_name", with: "Jaime")
```

But both will fail with:

```
  1) test signs up a user (Rocket.SignupTest)
     test/acceptance/signup_test.exs:4
     ** (Wallaby.ElementNotFound) Could not find element
     stacktrace:
       (wallaby) lib/wallaby/node.ex:342: Wallaby.Node.retry/2
       (wallaby) lib/wallaby/node.ex:81: Wallaby.Node.fill_in/3
       test/acceptance/signup_test.exs:8
```

I could make it work with the name attribute:

```elixir
fill_in(session, "user[name]", with: "Jaime")
```

I'm on Elixir 1.2.5, Phoenix 1.1.4, Ecto 1.1.7, Phantomjs 2.1.1.

**Comment by keathley** [comment]
Thanks for submitting this. I'll take a look asap. There is probably an issue with the xpath.

**Comment by DavidVII** [comment]
I'm curious regarding the label issue here. Shouldn't the `<label>`'s have a `for` attribute with the ID of the input field? For example:

```html
<label for="user_name">Name</label>
<input id="user_name" name="user[name]" type="text">
</div>
```

**Comment by jaimeiniesta** [comment]
@DavidVII you're very right, I forgot the `for` attribute. And with it, it now works finding them by the label :)

I've also found that it finds elements by ID, it's only that you should not append the "#", like:

```
fill_in(session, "#user_name", with: "Jaime") # this will not work
fill_in(session, "user_name", with: "Jaime")  # this works
```

So, I'm not sure if this is a bug. In any case, the [README](https://github.com/keathley/wallaby#interacting-with-forms) needs an update on this, in the example a "#" is used.

**Comment by keathley** [comment]
@DavidVII Good catch. :tada:

@jaimeiniesta: Looks like the README is wrong. The original reason for using the id selector was that it matched the field names generated by phoenix form helpers. For instance if you were building a form for a User and that User has a `first_name` key, you could just say `fill_in("user_first_name", with: "Chris")`. The README and other documentation should be updated to reflect that. It seems like that would help cut down on some confusion.

I'm wondering if there is a way that we could make this error more helpful. It seems like Wallaby could determine if you had some "bad" html (for instance forgetting a `for` attribute) and offer suggestions. Something like, "There is no field that matches "Name". There is a label element with the text "Name" but the element does not have a `for` attribute". I'm sure there's a better way to phrase that but I really like the idea of making the errors in Wallaby as helpful as possible.

**Comment by jaimeiniesta** [comment]
@keathley thanks for the explanation. It makes sense that when you're looking to `fill_in` an input, you look for it by its label or `name` attribute.

However, as `find` lets you find elements by their CSS selector, it looks a bit inconsistent to me that I can't also `fill_in` elements by their ID. I'd expect `fill_in('#user_first_name', with: "Joe")` to find the element (but, using the exact match, `#user_first_name`, not `user_first_name`:

* `#user_first_name` => CSS selector for an ID.
* `user[first_name]` => name attribute.
* `First Name` => a label.

> "There is no field that matches "Name". There is a label element with the text "Name" but the element does not have a for attribute".

:+1:

**Comment by jaimeiniesta** [comment]
After checking out [how Capybara does this](https://github.com/jnicklas/capybara/blob/master/lib/capybara/spec/session/fill_in_spec.rb), I've seen that it's just like Wallaby :) 

I guess it makes sense, `find` uses strict CSS selectors, but `fill_in` is more lax and can do a litte bit more magic to guess what input you're referring to. In that sense, you don't need to specify an exact CSS selector.

**Comment by keathley** [comment]
A lot of Wallaby's api was inspired by Capybara. But I'm not opposed to deviating from that api. I've gone back and forth on the id selector for fields as it tends to create confusion. I think part of the problem is that the documentation is misleading. We really aren't allowing fields to be filled in by their id. We're allowing them to be filled in by their, "generated by phoenix form helpers key". Updating the documentation might help alleviate some of that confusion. The alternative could be that we simply strip the `#` for the id selector.

**Comment by DavidVII** [comment]
Regarding the helpful error message: If we're allowing folks to find a field by it's name, id or label text, then maybe an error to say something like:

> No field found with "Selector" as it's id, name, or label.

This way the error tells you what the API expects. I believe capybara does something similar.

Also, allowing the octothorp (`#`) would be a nice. I feel that writing any of these should work:

```ex
fill_in "#first_name", with: "Something" # ID
fill_in "user[first_name]", with: "Something" # Name attribute
fill_in "First Name", with: "Something" # Label (uses `for` attr to locate input)
```

Just my two cents 😄

**Comment by keathley** [comment]
@DavidVII That verbiage seems good. 

My fear with including the `#` as a part of the query is that it will lead to confusion about using css selectors when interacting with form elements. It might encourage people to attempt to use class selectors for instance. I'd like to avoid encouraging the use of css selectors to find form fields.

Feature tests tend to be brittle because presentation and styling tends to be very fluid. For instance if you change a css class on an element you can easily break any number of tests. The goal of the label text and id selectors is to couple the tests to the underlying data instead of the presentation of that data. If I'm using the id selector I tend to think of it as "I'm filling in this key in a struct" rather then "I'm finding this form element". Honestly I try to put as much of this logic into named functions on a module that corresponds to a page or group of elements on a page. My tests then use those functions instead of calling into Wallaby directly. That way there is only one connection point between my tests and the underlying html.

Thinking through this I'd rather leave off the `#`. I think including it will just cause more confusion. This seems like a problem we can solve with better documentation and better errors. Does that seem reasonable?

**Comment by 1ternal** [comment]
same issue here. 😢 
I'm on Elixir 1.3.0-rc.0, Phoenix 1.2.0-rc,  Phantomjs 2.1.1.

**Comment by keathley** [comment]
@1ternal: did you read through the comments in this thread to see if they fix your issue? Or is it something else?

**Comment by DavidVII** [comment]
@keathley good points about the id 👍

**Comment by 1ternal** [comment]
@keathley 
fill_in with css id not working 😢 
`user_name` and `user[name]` works fine 😄 

`click("Button Name")`  not working ⛔ 
`click_button("Button Name")` worked 😸

**Comment by keathley** [comment]
The id selector doesn't work with the `#` by design. Based on the discussion in this thread we're going to update the documentation and work out some more descriptive errors to reduce this confusion.

`click_button` allows you to specify a buttons text. `click` is the underlying function used to click any node and doesn't do any searching based on text. I'm working on a refactor that should help remove this confusion as well. :+1:
