### ISSUE TITLE
Is it possible to write test without setup?

### ISSUE THREAD

**Issue by erickhsiao** [keathley/wallaby#52]
Hi. is that possible to write test like : 

```elixir
test "something" do 
end
```

without setup, and also skip 

```elixir
setup tag do 
  xxxx
  {:ok, conn: conn}
end
```

in ConnCase.

thanks.

**Comment by keathley** [comment]
your setup gets a `context` passed to it which includes the tags for the test. So if you wanted to selectively run pieces of your setup you could do something like this:

```elixir
setup context do
  unless context[:skip_some_setup] do
    setup_extra_stuff
  end
end

@tag :skip_some_setup
test "something" do
  # ...
end
```

You can read more about it in the docs here: http://elixir-lang.org/docs/stable/ex_unit/ExUnit.Case.html. Hope that helps. I'm going to close this since its not specifically an issue with Wallaby :+1:
